#pragma once

#include <vector>
#include <string>
#include <cstdio>
#include <stdexcept>

// C bindings generated by OpEn
extern "C" {
#include "nmpc_uav_obstacle_bindings.h"
}

namespace nmpc_uav {

struct OpEnResult {
    bool ok{false};
    std::vector<double> solution;
    std::string exit_status;
    double solve_time_ms{0.0};
    double cost{0.0};
};

class OpEnSolver {
public:
    OpEnSolver() = default;

    ~OpEnSolver() {
        if (cache_) {
            nmpc_uav_obstacle_free(cache_);
            cache_ = nullptr;
        }
    }

    void start() {
        cache_ = nmpc_uav_obstacle_new();
        if (!cache_) {
            throw std::runtime_error("Failed to create OpEn solver instance");
        }
        // Initialize warm-start buffer
        u_warm_.resize(NMPC_UAV_OBSTACLE_NUM_DECISION_VARIABLES, 0.0);
        fprintf(stderr, "[OpEn] Solver initialized (C bindings, no TCP)\n");
    }

    void kill_solver() { /* no-op */ }

    OpEnResult solve(const std::vector<double>& params) {
        OpEnResult result;

        if (!cache_) {
            result.exit_status = "NotInitialized";
            return result;
        }

        // u is in/out: on entry = initial guess, on exit = solution
        // Copy warm-start into working buffer
        std::vector<double> u_buf = u_warm_;

        // API: solve(instance, u, params, y0, c0)
        // y0 = nullptr → use default Lagrange multipliers
        // c0 = nullptr → use default penalty
        nmpc_uav_obstacleSolverStatus status = nmpc_uav_obstacle_solve(
            cache_,
            u_buf.data(),       // double* u (in/out)
            params.data(),      // const double* params
            nullptr,            // const double* y0
            nullptr             // const double* c0
        );

        // Copy solution
        result.solution = u_buf;

        // Store for warm-starting next call
        u_warm_ = u_buf;

        // Parse status
        result.solve_time_ms = static_cast<double>(status.solve_time_ns) / 1e6;
        result.cost = status.cost;

        switch (status.exit_status) {
            case nmpc_uav_obstacleConverged:
                result.exit_status = "Converged";
                result.ok = true;
                break;
            case nmpc_uav_obstacleNotConvergedIterations:
                result.exit_status = "NotConvergedIterations";
                result.ok = true;  // solution still usable
                break;
            case nmpc_uav_obstacleNotConvergedOutOfTime:
                result.exit_status = "NotConvergedOutOfTime";
                result.ok = true;
                break;
            case nmpc_uav_obstacleNotConvergedCost:
                result.exit_status = "NotConvergedCost";
                result.ok = false;
                break;
            case nmpc_uav_obstacleNotConvergedNotFiniteComputation:
                result.exit_status = "NotFiniteComputation";
                result.ok = false;
                break;
            default:
                result.exit_status = "Unknown";
                result.ok = false;
                break;
        }

        return result;
    }

private:
    nmpc_uav_obstacleCache* cache_{nullptr};
    std::vector<double> u_warm_;
};

}  // namespace nmpc_uav